version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: 
          name: Install dotnet tool
          command: dotnet tool install --global PowerShell
      - run: 
          name: Install Power apps tools
          shell: powershell.exe
          command: |
            $ProgressPreference = "SilentlyContinue"
            pwsh build/DownloadTools.ps1  